default: primary
variants:
# primary button
- name: primary
  context:
    label: Button with background primary
    mods: [primary]
# secondary button
- name: secondary
  context:
    label: Button with background secondary
    mods: [secondary]
# dark button
- name: dark
  context:
    label: Button dark
    mods: [dark]
# disabled button
- name: disabled
  context:
    label: Disabled button
    disabled: true
# button with image
- name: with-image
  context:
    image: /assets/images/icons/addToCart.png
    label: Button with image
    mods: [with-image]
# button with toggable multiple values (states)
- name: multiple-values
  context:
    label: multiple-values
    mods: [primary,fixed-width_medium]
    values:
      - value: 'Развернуть карту'
        visible: true
      - value: 'Свернуть карту'
# anchor like button
- name: primary-link
  context:
    label: Anchor(link) with background primary
    mods: [primary]
    href: '#!'
